### ISSUE TITLE
Too much boost raises an error

### ISSUE THREAD

**Issue by yncat** [yncat/screamingstrike#13]
Traceback (most recent call last):
  File "ss.py", line 28, in <module>
  File "ss.py", line 17, in main
  File "ssAppMain.py", line 280, in run
  File "ssAppMain.py", line 324, in play
  File "ssAppMain.py", line 569, in gamePlay
  File "gameField.py", line 85, in frameUpdate
  File "player.py", line 59, in frameUpdate
  File "player.py", line 74, in punchLaunch
  File "bgtsound.py", line 89, in pitch
  File "sound_lib\channel.py", line 207, in set_frequency
  File "sound_lib\channel.py", line 125, in set_attribute
  File "sound_lib\main.py", line 49, in bass_call
sound_lib.main.BassError: 20, an illegal parameter was specified

**Comment by yncat** [comment]
Fixed in the development branch.
