### ISSUE TITLE
Can't execute script SS successfully

### ISSUE THREAD

**Issue by Mudb0y** [yncat/screamingstrike#14]
I tried making some mods for fun and then trying to build and run the moddet game.
When running "python tools\build.sh" everything goes fine, but when running the generated play.exe i get an error.
I tried building the clean source with no modifications, and that failed too.

**Comment by yncat** [comment]
Please try compiling without --windowed option. Run the exe from cmd and debug using the traceback.

**Comment by Mudb0y** [comment]
I've compiled without the --windowed option, here's what i get:

C:\Users\stas\screamingstrike\dist\ss>ss                                                                    
Traceback (most recent call last):                                                                          
  File "ss.py", line 8, in <module>                                                                         
  File "c:\users\stas\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module                                                                   
    exec(bytecode, module.__dict__)                                                                         
  File "platform_utils\paths.py", line 19, in <module>                                                      
ModuleNotFoundError: No module named 'winpaths'                                                             
[10136] Failed to execute script ss                                                                         

I've installet winpaths from pypi and recompiled, but the error stil persists.
Could this happen because i'm compiling the game with a 32bit python installation?
I'm actually not surre if i have a 64bit python version or if i have a 32bit one. I know that my system is 64bit though.

**Comment by yncat** [comment]
Make sure you are compiling with 3.7.
Copying winpaths from the python directory to the project might solve the issue.
If nothing works, you could just drop winpaths and use environment variables instead.

**Comment by Mudb0y** [comment]
Oh. I used 3.8. I'll install 3.7 then.

**Comment by yncat** [comment]
Oh sorry, I should have written that in readme (I thought I had done it).
Once you successfully built it with 3.7, please close this issue.
