### ISSUE TITLE
error run the game 

### ISSUE THREAD

**Issue by ahmedthebest31** [yncat/screamingstrike#17]
Traceback (most recent call last):
  File "ss.py", line 28, in <module>
  File "ss.py", line 16, in main
  File "ssAppMain.py", line 56, in initialize
  File "window.py", line 33, in initialize
  File "accessible_output2\outputs\auto.py", line 12, in __init__
  File "accessible_output2\outputs\jaws.py", line 16, in __init__
  File "libloader\com.py", line 15, in load_com
  File "site-packages\win32com\client\gencache.py", line 534, in EnsureDispatch
  File "site-packages\win32com\client\gencache.py", line 391, in EnsureModule
  File "site-packages\win32com\client\gencache.py", line 266, in GetModuleForTypelib
  File "site-packages\win32com\client\gencache.py", line 552, in AddModuleToCache
AttributeError: module 'win32com.gen_py.F152C4EF-B92F-4139-A901-E8F1E28CC8E0x0x1x0' has no attribute 'CLSIDToClassMap'

**Comment by yncat** [comment]
Running this will solve the error.
```
import shutil
genpy_path=os.path.join(os.environ["temp"], "gen_py")
if os.path.isdir(genpy_path):
    shutil.rmtree(genpy_path)
    print("Cach cleared")
```
