### ISSUE TITLE
Can't build on mac

### ISSUE THREAD

**Issue by ogomez92** [yncat/screamingstrike#27]
I get the following error when running python tools/build.py after installing everything:

(ss) uri@Mac-mini-de-oriol screamingstrike % python tools/build.py
win=False, cwd=/Volumes/t7/code/pyGames/screamingstrike
Building ss. This will take several minutes. Please wait...
Executing: pyinstaller --windowed --onefile --osx-bundle-identifier com.nyanchanGames.screamingStrike2 ss.py
124 INFO: PyInstaller: 4.5.1
124 INFO: Python: 3.7.11 (conda)
133 INFO: Platform: Darwin-21.1.0-x86_64-i386-64bit
134 INFO: wrote /Volumes/t7/code/pyGames/screamingstrike/ss.spec
138 INFO: UPX is not available.
139 INFO: Extending PYTHONPATH with paths
['/Volumes/t7/code/pyGames/screamingstrike',
 '/Volumes/t7/code/pyGames/screamingstrike']
248 INFO: checking Analysis
249 INFO: Building Analysis because Analysis-00.toc is non existent
249 INFO: Initializing module dependency graph...
250 INFO: Caching module graph hooks...
255 INFO: Analyzing base_library.zip ...
1428 INFO: Processing pre-find module path hook distutils from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1429 INFO: distutils: retargeting to non-venv dir '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7'
2048 INFO: Caching module dependency graph...
2128 INFO: running Analysis Analysis-00.toc
2131 INFO: Analyzing /Volumes/t7/code/pyGames/screamingstrike/ss.py
2349 INFO: Processing pre-safe import module hook win32com from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
2518 INFO: Processing module hooks...
2518 INFO: Loading module hook 'hook-accessible_output2.py' from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
2519 INFO: Loading module hook 'hook-sound_lib.py' from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
2521 INFO: Loading module hook 'hook-encodings.py' from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks'...
2565 INFO: Loading module hook 'hook-pickle.py' from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks'...
2567 INFO: Loading module hook 'hook-heapq.py' from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks'...
2567 INFO: Loading module hook 'hook-difflib.py' from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks'...
2568 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks'...
2573 INFO: Loading module hook 'hook-xml.py' from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks'...
2601 INFO: Loading module hook 'hook-distutils.py' from '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks'...
2610 INFO: Looking for ctypes DLLs
2619 INFO: Analyzing run-time hooks ...
2621 INFO: Including run-time hook '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
2622 INFO: Including run-time hook '/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
2625 INFO: Looking for dynamic libraries
Traceback (most recent call last):
  File "/Users/uri/opt/anaconda3/envs/ss/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "/Volumes/t7/code/pyGames/screamingstrike/ss.spec", line 19, in <module>
    noarchive=False)
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 294, in __init__
    self.__postinit__()
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 159, in __postinit__
    self.assemble()
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 532, in assemble
    redirects=self.binding_redirects))
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/depend/bindepend.py", line 219, in Dependencies
    for lib, npth in selectImports(pth, xtrapath):
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/depend/bindepend.py", line 495, in selectImports
    dlls = getImports(pth)
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/depend/bindepend.py", line 753, in getImports
    return _getImports_macholib(pth)
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/PyInstaller/depend/bindepend.py", line 631, in _getImports_macholib
    m = MachO(pth)
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/macholib/MachO.py", line 118, in __init__
    self.load(fp)
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/macholib/MachO.py", line 133, in load
    self.load_header(fh, 0, size)
  File "/Users/uri/opt/anaconda3/envs/ss/lib/python3.7/site-packages/macholib/MachO.py", line 167, in load_header
    raise ValueError("Unknown Mach-O header: 0x%08x in %r" % (header, fh))
ValueError: Unknown Mach-O header: 0x7f454c46 in <_io.BufferedReader name='/Volumes/t7/code/pyGames/screamingstrike/sound_lib/lib/x64/libbass_alac.so'>
Copying sound_lib dlls...
Checking directory: dist/ss.app/Contents/Resources/accessible_output2 ... created
Copying accessible_output2 dlls...
Copying data files...
Copying locale files...
Copying readme
Copying changelog
Creating image dmg
Traceback (most recent call last):
  File "tools/build.py", line 92, in <module>
    dopackage()
  File "tools/build.py", line 22, in dopackage
    os.rename("dist/" + PROJECT + ".app", "dist/" + PROJECT_FULL_NAME + ".app")
OSError: [Errno 66] Directory not empty: 'dist/ss.app' -> 'dist/screamingStrike2.app'
(ss) uri@Mac-mini-de-oriol screamingstrike %

**Comment by yncat** [comment]
When I was creating the mac build in 2019, os.rename successfully renamed directories with contents in it. That behavior might have changed. As you may be watching this repo and already know, I'm planning a new release. I'm going to take a look at the issue at the release phase. I do not have my MBP right now; I will go back to Tokyo in Octover where I can retrieve mine.
The issue happens when trying to rename the app, so if you want to make a build right now, you can delete that line and the specific issue will be bypassed.

**Comment by yncat** [comment]
I think this issue was solved, at least in the 2.08 release time. I need to test with latest OSX version at some point, but just closing this stale issue.
